test_that("Converting and compiling runs succesfully", {


test_data <- structure(list(SEX = structure(0, label = "sexl", format.spss = "F8.0"), 
    serno = structure(0, label = "serno", format.spss = "F8.0"), 
    djob = structure(0, label = "djobl", format.spss = "F8.0"), 
    mjob = structure(0, label = "mjobl", format.spss = "F8.0"), 
    ft = structure(0, label = "ftl", format.spss = "F8.0"), empsta = structure(0, label = "empstal", format.spss = "F8.0"), 
    occ10 = structure(0, label = "OCCl", format.spss = "F8.0"), 
    sjd = structure(0, label = "sjdl", format.spss = "F8.0"), 
    pt = structure(0, label = "ptl", format.spss = "F8.0"), payp = structure(0, label = "paypl", format.spss = "F8.0"), 
    bpay = structure(0, label = "bpayl", format.spss = "F8.2"), 
    ovpay = structure(0, label = "ovpayl", format.spss = "F8.2"), 
    sppay = structure(0, label = "sppayl", format.spss = "F8.2"), 
    ipayall = structure(0, label = "ipayalll", format.spss = "F8.2"), 
    ipayin = structure(0, label = "ipayinl", format.spss = "F8.2"), 
    othpay = structure(0, label = "othpayl", format.spss = "F8.2"), 
    tpay = structure(0, label = "TPAYL", format.spss = "F8.2"), 
    gpay = structure(0, label = "gpayl", format.spss = "F8.2"), 
    hexo = structure(0, label = "hexol", format.spss = "F8.2"), 
    he = structure(0, label = "hel", format.spss = "F8.2"), 
    gpox = structure(0, label = "gpoxl", format.spss = "F8.2"), 
    hpay = structure(0, label = "hpayl", format.spss = "F8.2"), 
    lop = structure(0, label = "lopl", format.spss = "F8.0"), 
    adr = structure(0, label = "adrl", format.spss = "F8.0"), 
    anipay = structure(0, label = "anipayl", format.spss = "F8.2"), 
    agp = structure(0, label = "agpl", format.spss = "F8.2"), 
    bikfilter = structure(0, label = "bikfilterl", format.spss = "F8.0"), 
    bik = structure(0, label = "bikl", format.spss = "F8.2"), 
    alday = structure(0, label = "aldayl", format.spss = "F8.2"), 
    colag = structure(0, label = "colagl", format.spss = "F8.0"), 
    sano = structure(0, format.spss = "F8.0"), bhr = structure(0, label = "bhrl", format.spss = "F8.2"), 
    ovhrs = structure(0, label = "ovhrsl", format.spss = "F8.2"), 
    thrs = structure(0, label = "thrsl", format.spss = "F8.2"), 
    sic07 = structure(0, label = "newsic07", format.spss = "F8.0"), 
    age = structure(0, label = "agel", format.spss = "F8.0"), 
    SERNOL = structure(0, label = "SERNOL", format.spss = "F8.0"), 
    idbrsta = structure(0, label = "idbrsta", format.spss = "F8.0"), 
    idbrnemp = structure(0, format.spss = "F8.0"), hnuts4 = structure(0, format.spss = "A8"), 
    wnuts4 = structure(0, format.spss = "A8"), hcoa = structure(0, label = "OA03CD", format.spss = "A10", display_width = 10L), 
    wcoa = structure(0, label = "OA03CD", format.spss = "A10", display_width = 10L), 
    WLSOA = structure(0, label = "LSOA04CD", format.spss = "A254", display_width = 254L), 
    WMSOA = structure(0, label = "MSOA04CD", format.spss = "A254", display_width = 254L), 
    WGOR = structure(0, format.spss = "F8.0"), WPCT = structure(0, format.spss = "F8.0"), 
    WHA = structure(0, format.spss = "F8.0"), HLSOA = structure(0, label = "LSOA04CD", format.spss = "A254", display_width = 254L), 
    HMSOA = structure(0, label = "MSOA04CD", format.spss = "A254", display_width = 254L), 
    HGOR = structure(0, format.spss = "F8.0"), HPCT = structure(0, format.spss = "F8.0"), 
    HHA = structure(0, format.spss = "F8.0"), pubpriv = structure(0, format.spss = "F8.0"), 
    luref = structure(0, format.spss = "A11", display_width = 11L), 
    bpayinc = structure(0, format.spss = "F8.2"), MISS_IND = structure(0, format.spss = "A64", display_width = 64L), 
    imp = structure(0, format.spss = "F8.0"), STRATUM = structure(0, format.spss = "A1", display_width = 1L), 
    dweight = structure(0, label = "Design Weight", format.spss = "F8.2"), 
    gweight = structure(0, format.spss = "F8.2"), 
    calwght = structure(0, format.spss = "F8.2"), 
    lpdweight = structure(0, label = "Design Weight", format.spss = "F8.2"), 
    lpgweight = structure(0, format.spss = "F8.2"), 
    lpcalwght = structure(0, format.spss = "F8.2"), 
    cosp = structure(0, label = "cospl", format.spss = "F8.0"), 
    year = structure(0, label = "year", format.spss = "F8.0"), 
    numstrata = structure(0, format.spss = "F8.0"), warea = structure(0, label = "ASHE_AREA_CODE_2", format.spss = "A9", display_width = 9L), 
    harea = structure(0, label = "ASHE_AREA_CODE_2", format.spss = "A9", display_width = 9L), 
    wla = structure(0, label = "LAD13CD", format.spss = "A9", display_width = 9L), 
    hla = structure(0, label = "LAD13CD", format.spss = "A9", display_width = 9L), 
    wpc = structure(0, label = "PCON10CD", format.spss = "A9", display_width = 9L), 
    hpc = structure(0, label = "PCON10CD", format.spss = "A9", display_width = 9L), 
    wttw = structure(0, label = "TTWA07CD", format.spss = "A9", display_width = 9L), 
    httw = structure(0, label = "TTWA07CD", format.spss = "A9", display_width = 9L), 
    hnuts1 = structure(0, label = "NUTS112CD", format.spss = "A9", display_width = 9L), 
    wnuts1 = structure(0, label = "NUTS112CD", format.spss = "A9", display_width = 9L), 
    hnuts2 = structure(0, label = "NUTS212CD", format.spss = "A9", display_width = 9L), 
    wnuts2 = structure(0, label = "NUTS212CD", format.spss = "A9", display_width = 9L), 
    hnuts3 = structure(0, label = "NUTS312CD", format.spss = "A9", display_width = 9L), 
    wnuts3 = structure(0, label = "NUTS312CD", format.spss = "A9", display_width = 9L), 
    app = structure(0, label = "Appl", format.spss = "F8.0"), 
    appdate = structure(0, format.spss = "F8.0"), WCCG = structure(0, label = "CCG13CD", format.spss = "A9", display_width = 9L), 
    WHLTH = structure(0, label = "HLTH13CD", format.spss = "A9", display_width = 9L), 
    WLAU1 = structure(0, label = "LAU113CD", format.spss = "A7", display_width = 7L), 
    WWAC = structure(0, label = "NAWC11CD", format.spss = "A9", display_width = 9L), 
    WSPC = structure(0, label = "SPC11CD", format.spss = "A9", display_width = 9L), 
    HCCG = structure(0, label = "CCG13CD", format.spss = "A9", display_width = 9L), 
    HHLTH = structure(0, label = "HLTH13CD", format.spss = "A9", display_width = 9L), 
    HLAU1 = structure(0, label = "LAU113CD", format.spss = "A7", display_width = 7L), 
    HWAC = structure(0, label = "NAWC11CD", format.spss = "A9", display_width = 9L), 
    HSPC = structure(0, label = "SPC11CD", format.spss = "A9", display_width = 9L), 
    lgd14h = structure(0, label = "lgd14hl", format.spss = "A9", display_width = 9L), 
    lgd14w = structure(0, label = "lgd14wl", format.spss = "A9", display_width = 9L), 
    WLAU1NAT = structure(0, label = "LAU114NATCD", format.spss = "A9", display_width = 9L), 
    WWER = structure(0, label = "NAWER11CD", format.spss = "A9", display_width = 9L), 
    WSPR = structure(0, label = "SPR11CD", format.spss = "A9", display_width = 9L), 
    HLAU1NAT = structure(0, label = "LAU114NATCD", format.spss = "A9", display_width = 9L), 
    HWER = structure(0, label = "NAWER11CD", format.spss = "A9", display_width = 9L), 
    HSPR = structure(0, label = "SPR11CD", format.spss = "A9", display_width = 9L), 
    ppstart = structure(0, label = "ppstartl", format.spss = "A6", display_width = 6L), 
    hrpayx = structure(0, format.spss = "F8.2"), nlpflag = structure(0, format.spss = "F8.0"), 
    piden = structure(0, format.spss = "A10", display_width = 10L), 
    PCFlag = structure(0, format.spss = "F8.0"), wleps1 = structure(0, label = "LEP17CD1new", format.spss = "A9", display_width = 9L), 
    wleps2 = structure(0, label = "LEP17CD2new", format.spss = "A9", display_width = 9L), 
    hleps1 = structure(0, label = "LEP17CD1new", format.spss = "A9", display_width = 9L), 
    hleps2 = structure(0, label = "LEP17CD2new", format.spss = "A9", display_width = 9L), 
    LOPF = structure(0, format.spss = "F8.0"), furlough = structure(0, label = "furlought", format.spss = "F8.0"), 
    lpdweightf = structure(0, label = "Design Weight", format.spss = "F8.2"), 
    lpgweightf = structure(0, format.spss = "F8.2"), 
    WITL1 = structure(0, label = "ITL121CD", format.spss = "A3", display_width = 3L), 
    WITL2 = structure(0, label = "ITL221CD", format.spss = "A4", display_width = 4L), 
    WITL3 = structure(0, label = "ITL321CD", format.spss = "A5", display_width = 5L), 
    HITL1 = structure(0, label = "ITL121CD", format.spss = "A3", display_width = 3L), 
    HITL2 = structure(0, label = "ITL221CD", format.spss = "A4", display_width = 4L), 
    HITL3 = structure(0, label = "ITL321CD", format.spss = "A5", display_width = 5L), 
    lpcalwgtf = structure(0, format.spss = "F8.2"), 
    acthrs = structure(0, format.spss = "F8.2"), payperc = structure(0, format.spss = "F8.2")), row.names = c(NA, 
-1L), class = c("tbl_df", "tbl", "data.frame"))


  test_convert_compile <- function() {

    withr::local_envvar(DATA_DIRECTORY = ".")

    ashe_convert("test", "test_rds_data/")

    ashe_compile("test_rds_data", save_to_folder = TRUE)

    lfs <- ashe_load()
  }

  withr::with_file(list(fs::dir_create("test"),
    fs::dir_create("test_rds_data"),
    "test/ashe_2011_2017_GB_v12.sav" = haven::write_sav(test_data, "test/ashe_2011_2017_GB_v12.sav"),
    "test/ashe_2018_2019_GB_v12.sav" = haven::write_sav(test_data, "test/ashe_2018_2019_GB_v12.sav"),
    "data_ashe_raw.fst",
    "ashe_variables_report.csv"
  ), {
    expect_error(suppressMessages(test_convert_compile()), NA)
  })


})

